name: Development e2e API

on: [pull_request, workflow_dispatch]

jobs:
  cypress-e2e-api-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Cypress Run
        uses: cypress-io/github-action@v5.0.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: API E2E TEST
          spec: api/api/cypress/e2e/*
        env: 
          APP_ID: ${{ secrets.APP_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
