name: Development e2e API

on: [pull_request, workflow_dispatch]

jobs:
  cypress-e2e-api-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Install Dependencies
        run: yarn install

      - name: Run E2E Tests
        env:
          APP_ID: ${{ secrets.APP_ID }}
        run: yarn cypress run --project ./api

      - name: Upload Results to Tesults
        env: 
          TESULTS_TOKEN: ${{ secrets.TESULTS_TOKEN }}
        run: 