name: Development e2e API

on: [pull_request, workflow_dispatch]

jobs:
  cypress-e2e-api-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress
        run:
          npx cypress run --project ./src/tests/ --record --key $CYPRESS_RECORD_KEY
        env: 
          APP_ID: ${{ secrets.APP_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
