name: Development e2e Api-Web

on: [pull_request, workflow_dispatch]

jobs:
  cypress-e2e-api-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Run Api Cypress Tests 🧪
        uses: cypress-io/github-action@v5
        env: 
          APP_ID: ${{ secrets.APP_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          browser: electron
          command: npm run e2e:api

  cypress-e2e-amazon-tests:
      runs-on: ubuntu-latest
      container: 
        image: cypress/browsers:node18.12.0-chrome103-ff107
        options: --user 1001
      needs: [ cypress-e2e-api-tests ]
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Install dependencies
          run: yarn install

        - name: Run Amazon Cypress Tests 🧪
          env: 
           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
           browser: electron
           command: npm run e2e:amazon

  cypress-e2e-avenue-tests:
      runs-on: ubuntu-latest
      container: 
        image: cypress/browsers:node18.12.0-chrome103-ff107
        options: --user 1001
      needs: [ cypress-e2e-api-tests ]
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Install dependencies
          run: yarn install

        - name: Run Avenue Cypress Tests 🧪
          env: 
           APP_ID: ${{ secrets.APP_ID }}
           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
           browser: electron
           command: npm run e2e:avenue
